modu-hospital/modu_hospital

- controllers/user.controller.js
- middleware/auth.middleware.js
- migrations/20230228013316-create-reservation.js
- migrations/20230228013721-create-hospital.js
- models/hospital.js
- models/index.js
- models/reservation.js
- models/user.js
- models/workingtime.js
- repositories/user.repository.js
- routes/index.js
- services/user.service.js
migrate, models 추가 및 수정/ 회원가입 구현 중(수정할 거 있음)
> [수정] migrate, models

- routes/hospital.route.js
- routes/hospital.routes.js
- routes/index.js
hospital.routes.js 랑 hospital.route.js 두개 있어서 한 개 삭제함
> [삭제] hospital.route.js 파일 삭제

- controllers/hospital.controller.js
- middleware/validation.js
- repositories/hospital.repository.js
- routes/hospital.routes.js
- services/hospital.service.js
- services/user.service.js
[추가] 병원 예약관리 조회,  예약날짜 수정, 승인하기, 승인대기목록 불러오기, 병원 정보등록
> [추가] 병원 페이지 등록 및 예약관리 검증 추가

- controllers/user.controller.js
- repositories/hospital.repository.js
- repositories/reservation.repository.js
- repositories/user.repository.js
- routes/index.js
- routes/user.routes.js
- services/reservation.service.js
- services/user.service.js
> [추가] mypage get, 예약취소, 리뷰작성 기능 추가. reservation service 및 repository 추가

- migrations/20230302012559-delete_table_pharmacies.js
> [수정] 약국 테이블 삭제

- app.js
- controllers/user.controller.js
- repositories/user.repository.js
- routes/admin.routes.js
- services/user.service.js
- views/index.ejs
Page/admin으로 변경
feature/admin 삭제
> [수정] 브랜치명 변경

- app.js
- controllers/user.controller.js
- lib/errors.js
- middleware/errorhandler.js
- models/doctor.js
- services/reservation.service.js
Errorhandler 사용법
1. lib/errors.js -> CreateError 클래스 안에 Error 케이스 작성
2. service -> lib/errors(CreateError) 임포트,  CreateError로 에러 생성, throw
3. controller -> catch(err) 문 안의 next(err)로 생성된 에러를 errorHandler 미들웨어로 전송
4. Middleware/errorhandler.js -> 각 api별로 발생하는 에러 케이스들 처리, 리턴
작동 흐름 : service/controller에서 lib/errors에 작성되어 있는 / 알 수 없는 에러 발생 -> controller에서 catch ->  errorhandler middleware에서 처리 -> 리턴
*joi에서 발생한 에러들도 errorhandler에서 처리 가능함
참고 : api/users/mypage/cancel/:userId
> [수정] errorhandler 완성

- controllers/hospital.controller.js
- repositories/hospital.repository.js
- views/hospital.ejs
> [수정] git add 하는 과정에서 삭제된 코드 복구 및 에러 해결

- controllers/hospital.controller.js
- models/doctor.js
- repositories/hospital.repository.js
- routes/hospital.routes.js
- services/hospital.service.js
- views/hospital.ejs
- views/js/reservationlist.js
hospital repository에 date format 및 코드 로직 변경함
> [추가] api 병원 예약,승인,대기 조회 코드 수정 및 추가, 프론트 추가

- controllers/hospital.controller.js
- controllers/refreshToken.controller.js
- controllers/user.controller.js
- lib/errors.js
- middleware/auth.middleware.js
- middleware/errorhandler.js
- migrations/20230303011145-create-refresh-token.js
- migrations/20230303014834-delete_table_refresh-tokens.js
- migrations/20230303020452-create-refresh-token.js
- migrations/20230303020948-delete_table_RefreshTokens.js
- migrations/20230303021220-create-refresh-token.js
- migrations/20230306112226-addcolumn.js
- migrations/20230306122631-modify_hospitals_deleteAt_deletedAt.js
- models/hospital.js
- models/refreshtoken.js
- models/user.js
- package-lock.json
- repositories/refreshToken.repository.js
- repositories/reservation.repository.js
- repositories/user.repository.js
- routes/ejs.routes.js
- routes/index.js
- routes/refreshToken.routes.js
- routes/user.routes.js
- services/hospital.service.js
- services/refreshToken.service.js
- services/reservation.service.js
- services/user.service.js
- views/mypage.ejs
> [수정] mypage GET API 수정

- controllers/workingtime.controller.js
- repositories/workingTime.repository.js
- routes/workingtime.routes.js
- services/workingTime.service.js
- views/hospitalEdit.ejs
- views/index.ejs
- views/js/calculationtime.js
- views/js/reservation.js
- views/js/road.js
- views/reservation.ejs
> [기타] dev체리픽

- controllers/user.controller.js
- middleware/auth.middleware.js
- migrations/20230321000224-reservation_add_address.js
- routes/ejs.routes.js
- routes/user.routes.js
- services/hospital.service.js
- views/header.ejs
- views/hospitalDetail.ejs
- views/index.ejs
- views/js/logout.js
- views/login.ejs
- views/signup.ejs
마이그레이션 reservation에 주소 컬럼 추가, 로그인, 로그아웃 회원가입 끝
> [추가]마이그레이션

- controllers/token.controller.js
- controllers/user.controller.js
- middleware/auth.middleware.js
- repositories/token.repository.js
- routes/ejs.routes.js
- routes/hospital.routes.js
- services/token.service.js
- services/user.service.js
- views/hospitaldetail.ejs
> [수정] 병원상세페이지

- controllers/token.controller.js
- controllers/user.controller.js
- middleware/auth.middleware.js
- routes/ejs.routes.js
- routes/token.routes.js
- views/hospitaldetail.ejs
> [수정] 토큰 재발급 진행

- controllers/token.controller.js
- controllers/user.controller.js
- views/hospitaldetail.ejs
> [추가] 로그인 유지

- controllers/token.controller.js
- controllers/user.controller.js
- views/hospital.ejs
- views/hospitaldetail.ejs
> [기타] dev -> main 병합

- controllers/token.controller.js
- controllers/user.controller.js
- repositories/hospital.repository.js
- services/hospital.service.js
- services/user.service.js
- views/header.ejs
- views/hospitaldetail.ejs
- views/index.ejs
- views/login.ejs
- views/partner.ejs
- views/signup.ejs
> [수정] 프론트 및 오류해결

- repositories/reservation.repository.js
- repositories/workingTime.repository.js
- routes/workingtime.routes.js
- services/workingTime.service.js
> [수정] SQL문 escape문 변경

- controllers/token.controller.js
- controllers/user.controller.js
- middleware/auth.middleware.js
- middleware/errorhandler.js
- package-lock.json
- package.json
- routes/ejs.routes.js
- services/reservation.service.js
- services/user.service.js
- views/index.ejs
- views/js/calculationtime.js
- views/js/main.js
- views/js/notice.js
- views/js/tabmenu.js
- views/js/token.js
- views/mypage.ejs
- views/signup.ejs
메인페이지 로그인 안내 화살표 1번만 뜨도록 변경,
마이페이지 조회시 불러올 정보가 없을때 무한알럿 뜨는 문제 해결
tabmenu.js 복구
> [수정] 메인, 마이페이지 조회

- views/partner.ejs
일반회원, 파트너회원 가입페이지 비번 조건 함수 확인란과 입력란에 통일 적용
> [수정]signupejs 비밀번호 함수 통일 적용

- routes/ejs.routes.js
> [수정] 로그인 안내 수정

- views/header.ejs
- views/hospitaldetail.ejs
- views/mypage.ejs
> [수정] 마이페이지 페이지네이션

- __test__/unit/services/hospital.service.spec.js
- __test__/unit/services/user.service.spec.js
- controllers/user.controller.js
- services/hospital.service.js
> [수정] hospital service test code

- __test__/unit/controllers/workingtime.controller.spec.js
- __test__/unit/services/workingtime.service.spec.js
- controllers/user.controller.js
- lib/validation.js
- middleware/auth.middleware.js
- repositories/user.repository.js
- routes/user.routes.js
- services/user.service.js
- services/workingTime.service.js
- views/js/reservation.js
- views/mypage.ejs
- views/reservation.ejs
> [추가] workingtime 테스트 코드
